/**
 * React Native App
 * https://github.com/ztplz/CNode-react-native
 * email: mysticzt@gmail.com
 */

export const TIME_OUT = 'TIME_OUT';

export const CHANGE_MODE = 'CHANGE_MODE';
export const CHANGE_THEMECOLOR = 'CHANGE_THEMECOLOR';
export const USER_LOGIN = 'USER_LOGIN';
export const START_UP = 'START_UP';
export const GET_USERINFO_SUCCESS = 'GET_USERINFO_SUCCESS';

export const FETCH_HOMEPAGE_DATA = 'FETCH_HOMEPAGE_DATA';
export const FETCH_HOMEPAGE_DATA_SUCCESS = 'FETCH_HOMEPAGE_DATA_SUCCESS';
export const FETCH_HOMEPAGE_DATA_FAILURE = 'FETCH_HOMEPAGE_DATA_FAILURE';
export const REFRESH_HOMEPAGE_DATA = 'REFRESH_HOMEPAGE_DATA';
export const REFRESH_HOMEPAGE_DATA_SUCCESS = 'REFRESH_HOMEPAGE_DATA_SUCCESS';
export const REFRESH_HOMEPAGE_DATA_FAILURE = 'REFRESH_HOMEPAGE_DATA_FAILURE';
export const FETCH_MORE_HOMEPAGE_DATA = 'FETCH_MORE_HOMEPAGE_DATA';
export const FETCH_MORE_HOMEPAGE_DATA_SUCCESS = 'FETCH_MORE_HOMEPAGE_DATA_SUCCESS';
export const FETCH_MORE_HOMEPAGE_DATA_FAILURE = 'FETCH_MORE_HOMEPAGE_DATA_FAILURE';
export const LOADED_ALL_DATA = 'LOADED_ALL_DATA';

export const FETCH_TOPICDETAIL_DATA = 'FETCH_TOPICDETAIL_DATA';
export const FETCH_TOPICDETAIL_DATA_SUCCESS = 'FETCH_TOPICDETAIL_DATA_SUCCESS';
export const FETCH_TOPICDETAIL_DATA_FAILURE = 'FETCH_TOPICDETAIL_DATA_FAILURE';
export const REFRESH_TOPICDETAIL_DATA = 'REFRESH_TOPICDETAIL_DATA';
export const REFRESH_TOPICDETAIL_DATA_SUCCESS = 'REFRESH_TOPICDETAIL_DATA_SUCCESS';
export const REFRESH_TOPICDETAIL_DATA_FAILURE = 'REFRESH_TOPICDETAIL_DATA_FAILURE';
export const REPLY_TO_TOPIC = 'REPLY_TO_TOPIC';
export const SENT_REPLY_MESSAGE = 'SENT_REPLY_MESSAGE';
export const COLLECT_TOPIC = 'COLLECT_TOPIC';
export const COLLECT_TOPIC_SUCCESS = 'COLLECT_TOPIC_SUCCESS';
export const COLLECT_TOPIC_FAILURE = 'COLLECT_TOPIC_FAILURE';
export const NOT_COLLECT_TOPIC = 'NOT_COLLECT_TOPIC';
export const NOT_COLLECT_TOPIC_SUCCESS = 'NOT_COLLECT_TOPIC_SUCCESS';
export const NOT_COLLECT_TOPIC_FAILURE = 'NOT_COLLECT_TOPIC_FAILURE';
export const UPED_ITEM = 'UPED_ITEM';

export const UNREAD_MESSAGE_REPLY_TEXTINPUT_SHOW = 'UNREAD_MESSAGE_REPLY_TEXTINPUT_SHOW';
export const UNREADMESSAGE_REPLY = 'UNREADMESSAGE_REPLY';
export const FETCH_UNREADMESSAGE_DATA = 'FETCH_UNREADMESSAGE_DATA';
export const FETCH_UNREADMESSAGE_DATA_SUCCESS = 'FETCH_UNREADMESSAGE_DATA_SUCCESS';
export const FETCH_UNREADMESSAGE_DATA_FAILURE = 'FETCH_UNREADMESSAGE_DATA_FAILURE';
export const REFRESH_UNREADMESSAGE_DATA = 'REFRESH_UNREADMESSAGE_DATA';
export const REFRESH_UNREADMESSAGE_DATA_SUCCESS = 'REFRESH_UNREADMESSAGE_DATA_SUCCESS';
export const REFRESH_UNREADMESSAGE_DATA_FAILURE = 'REFRESH_UNREADMESSAGE_DATA_FAILURE';

export const HAVEREAD_MESSAGE_REPLY_TEXTINPUT_SHOW = 'HAVEREAD_MESSAGE_REPLY_TEXTINPUT_SHOW';
export const HAVEREADMESSAGE_REPLY = 'HAVEREADMESSAGE_REPLY';
export const FETCH_HAVEREADMESSAGE_DATA = 'FETCH_HAVEREADMESSAGE_DATA';
export const FETCH_HAVEREADMESSAGE_DATA_SUCCESS = 'FETCH_HAVEREADMESSAGE_DATA_SUCCESS';
export const FETCH_HAVEREADMESSAGE_DATA_FAILURE = 'FETCH_HAVEREADMESSAGE_DATA_FAILURE';
export const REFRESH_HAVEREADMESSAGE_DATA = 'REFRESH_HAVEREADMESSAGE_DATA';
export const REFRESH_HAVEREADMESSAGE_DATA_SUCCESS = 'REFRESH_HAVEREADMESSAGE_DATA_SUCCESS';
export const REFRESH_HAVEREADMESSAGE_DATA_FAILURE = 'REFRESH_HAVEREADMESSAGE_DATA_FAILURE';

export const GET_DRAFTBOX_DATA = 'GET_DRAFTBOX_DATA';
export const SAVE_DRAFT_DATA = 'SAVE_DRAFT_DATA';

export const FETCH_USERDETAIL_DATA = 'FETCH_USERDETAIL_DATA';
export const FETCH_USERDETAIL_DATA_SUCCESS = 'FETCH_USERDETAIL_DATA_SUCCESS';
export const FETCH_USERDETAIL_DATA_FAILURE = 'FETCH_USERDETAIL_DATA_FAILURE';

export const FETCH_COLLECTION_DATA = 'FETCH_COLLECTION_DATA';
export const FETCH_COLLECTION_DATA_SUCCESS = 'FETCH_COLLECTION_DATA_SUCCESS';
export const FETCH_COLLECTION_DATA_FAILURE = 'FETCH_COLLECTION_DATA_FAILURE';
export const REFRESH_COLLECTION_DATA = 'REFRESH_COLLECTION_DATA';
export const REFRESH_COLLECTION_DATA_SUCCESS = 'REFRESH_COLLECTION_DATA_SUCCESS';
export const REFRESH_COLLECTION_DATA_FAILURE = 'REFRESH_COLLECTION_DATA_FAILURE';

export const LOGIN_TO_CNODE = 'LOGIN_TO_CNODE';
export const LOGIN_TO_CNODE_SUCCESS = 'LOGIN_TO_CNODE_SUCCESS';
export const LOGIN_TO_CNODE_FAILURE = 'LOGIN_TO_CNODE_FAILURE';
export const RETRY_TO_LOGIN = 'RETRY_TO_LOGIN';

// export const FETCH_RECENT_TOPICS = 'FETCH_RECENT_TOPICS';
// export const FETCH_RECENT_TOPICS_SUCCESS = 'FETCH_RECENT_TOPICS_SUCCESS';
// export const FETCH_RECENT_TOPICS_FAILURE = 'FETCH_RECENT_TOPICS_FAILURE';
export const REFRESH_RECENT_DETAIL = 'REFRESH_RECENT_DETAIL';
export const REFRESH_RECENT_DETAIL_SUCCESS = 'REFRESH_RECENT_DETAIL_SUCCESS';
export const REFRESH_RECENT_DETAIL_FAILURE = 'REFRESH_RECENT_DETAIL_FAILURE';

export const FETCH_ME_DATA = 'FETCH_ME_DATA';
export const FETCH_ME_DATA_SUCCESS = 'FETCH_ME_DATA_SUCCESS';
export const FETCH_ME_DATA_FAILURE = 'FETCH_ME_DATA_FAILURE';

export const FETCH_MESSAGE = 'FETCH_MESSAGE';
export const FETCH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS';
export const FETCH_MESSAGE_FAILURE = 'FETCH_MESSAGE_FAILURE';
